manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: taz
      url-base: https://github.com/thazhemadam
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboard-totem-7racker
      remote: taz
      revision: main
    - name: zmk-keyboard-kaizen
      remote: taz
      revision: main
  self:
    path: config
