manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: taz
      url-base: https://github.com/thazhemadam
    - name: fingerpunch
      url-base: https://github.com/sadekbaroudi
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: urob
      url-base: https://github.com/urob
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll-ptp
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-fingerpunch-vik
      remote: fingerpunch
      revision: main
      import: config/deps.yml
    - name: zmk-keyboard-totem-7racker
      remote: taz
      revision: main
    - name: zmk-keyboard-kaizen
      remote: taz
      revision: main
    - name: zmk-keyboard-chocV
      remote: taz
      revision: main
    - name: maxtouch-zephyr-module
      remote: petejohanson
      revision: main
      import: config/west.yml
  self:
    path: config
