manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: taz
      url-base: https://github.com/thazhemadam
    - name: fingerpunch
      url-base: https://github.com/sadekbaroudi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-fingerpunch-vik
      remote: fingerpunch
      revision: main
      import: config/deps.yml
    - name: zmk-keyboard-totem-7racker
      remote: taz
      revision: main
    - name: zmk-keyboard-kaizen
      remote: taz
      revision: main
  self:
    path: config
