name: "Draw ZMK keymaps"
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**.keymap"
      - "config/**.dtsi"
      - "keymap-drawer/config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: "write"
    with:
      commit_message: "docs: draw keymaps with keymap-drawer"
      config_path: "keymap-drawer/config.yaml"  # config file, ignored if not exists
      fail_on_error: true
      install_branch: "main"
      json_path: "keymap-drawer/layouts"
      keymap_patterns: "config/!(base).keymap"  # path to the keymaps to parse
      output_folder: "assets"            # path to save produced SVG and keymap YAML files
      west_config_path: "config"
      parse_args: ""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: ""   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
